name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # Wait for CI to pass before creating release
  wait-for-ci:
    name: Wait for CI
    runs-on: ubuntu-latest
    steps:
      - name: Wait for CI workflow
        uses: lewagon/wait-on-check-action@v1.3.3
        with:
          ref: ${{ github.ref }}
          check-name: 'All Quality Checks Passed'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  # Create GitHub Release after CI passes
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: wait-for-ci
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create release notes
        id: notes
        run: |
          echo "## Cadabra PHP Client v${{ steps.version.outputs.version }}" > /tmp/release-notes.md
          echo "" >> /tmp/release-notes.md
          echo "PHP client and Symfony bundle for Cadabra query cache." >> /tmp/release-notes.md
          echo "" >> /tmp/release-notes.md
          echo "### Installation" >> /tmp/release-notes.md
          echo '```bash' >> /tmp/release-notes.md
          echo "composer require cadabra/php:^${{ steps.version.outputs.version }}" >> /tmp/release-notes.md
          echo '```' >> /tmp/release-notes.md
          echo "" >> /tmp/release-notes.md
          echo "### Requirements" >> /tmp/release-notes.md
          echo "- PHP 8.1+" >> /tmp/release-notes.md
          echo "- Symfony 6.0+ or 7.0+" >> /tmp/release-notes.md
          echo "- Doctrine DBAL 3.0+ or 4.0+" >> /tmp/release-notes.md
          echo "- Cadabra server running (see [cadabra](https://github.com/SebastiaanWouters/cadabra))" >> /tmp/release-notes.md

          cat /tmp/release-notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.version }}
          body_path: /tmp/release-notes.md
          draft: false
          prerelease: ${{ contains(steps.version.outputs.version, '-') }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Summary
        run: |
          echo "✅ GitHub Release created: ${{ steps.version.outputs.tag }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Packagist will automatically detect this release via webhook." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "View release: https://github.com/${{ github.repository }}/releases/tag/${{ steps.version.outputs.tag }}" >> $GITHUB_STEP_SUMMARY
          echo "View on Packagist: https://packagist.org/packages/cadabra/php" >> $GITHUB_STEP_SUMMARY
